///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AgregarGlosa recording.
    /// </summary>
    [TestModule("c9c1037d-78d9-47ad-b116-5315b09a719b", ModuleType.Recording, 1)]
    public partial class AgregarGlosa : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static AgregarGlosa instance = new AgregarGlosa();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AgregarGlosa()
        {
            Cantidad = "1";
            Valor = "21954";
            ObservacionGlosa = "Prueba Glosa";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AgregarGlosa Instance
        {
            get { return instance; }
        }

#region Variables

        string _Cantidad;

        /// <summary>
        /// Gets or sets the value of variable Cantidad.
        /// </summary>
        [TestVariable("ff89207b-ca2e-4d10-b7b1-54309ae1ff25")]
        public string Cantidad
        {
            get { return _Cantidad; }
            set { _Cantidad = value; }
        }

        string _Valor;

        /// <summary>
        /// Gets or sets the value of variable Valor.
        /// </summary>
        [TestVariable("6828dc91-cf10-4e8e-9ad9-ce9f32c7f4d3")]
        public string Valor
        {
            get { return _Valor; }
            set { _Valor = value; }
        }

        string _ObservacionGlosa;

        /// <summary>
        /// Gets or sets the value of variable ObservacionGlosa.
        /// </summary>
        [TestVariable("8d7ed7f5-5ac7-46cc-bc5e-fd6a7407c939")]
        public string ObservacionGlosa
        {
            get { return _ObservacionGlosa; }
            set { _ObservacionGlosa = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Cantidad' with focus on 'MDIPrincipal.Txt_CantidadGlosas'.", repo.MDIPrincipal.Txt_CantidadGlosasInfo, new RecordItemIndex(0));
            repo.MDIPrincipal.Txt_CantidadGlosas.PressKeys(Cantidad);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Valor' with focus on 'MDIPrincipal.Txt_ValorGlosa'.", repo.MDIPrincipal.Txt_ValorGlosaInfo, new RecordItemIndex(1));
            repo.MDIPrincipal.Txt_ValorGlosa.PressKeys(Valor);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ObservacionGlosa' with focus on 'MDIPrincipal.Txt_ObservacionGlosa'.", repo.MDIPrincipal.Txt_ObservacionGlosaInfo, new RecordItemIndex(2));
            repo.MDIPrincipal.Txt_ObservacionGlosa.PressKeys(ObservacionGlosa);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Btn_AgregarGlosa' at Center.", repo.MDIPrincipal.Btn_AgregarGlosaInfo, new RecordItemIndex(3));
            repo.MDIPrincipal.Btn_AgregarGlosa.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormHash32770.Btn_AceptarVolanteAutor' at Center.", repo.FormHash32770.Btn_AceptarVolanteAutorInfo, new RecordItemIndex(4));
            repo.FormHash32770.Btn_AceptarVolanteAutor.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.BtGlosas' at 52;12.", repo.MDIPrincipal.BtGlosasInfo, new RecordItemIndex(5));
            repo.MDIPrincipal.BtGlosas.Click("52;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ModuloDeGlosas.Txt_CantidaFilaGlosa'.", repo.ModuloDeGlosas.Txt_CantidaFilaGlosaInfo, new RecordItemIndex(6));
            Validate.Exists(repo.ModuloDeGlosas.Txt_CantidaFilaGlosaInfo);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(7));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
