///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BuscarVolante recording.
    /// </summary>
    [TestModule("d6ae6395-3e06-4ca2-8772-9774827bfcd7", ModuleType.Recording, 1)]
    public partial class BuscarVolante : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static BuscarVolante instance = new BuscarVolante();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BuscarVolante()
        {
            Volante = "141031331";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BuscarVolante Instance
        {
            get { return instance; }
        }

#region Variables

        string _Volante;

        /// <summary>
        /// Gets or sets the value of variable Volante.
        /// </summary>
        [TestVariable("dc50f890-4497-46ed-9100-526645818e3f")]
        public string Volante
        {
            get { return _Volante; }
            set { _Volante = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.BtI_nformacionAutorizaciones' at Center.", repo.MDIPrincipal.BtI_nformacionAutorizacionesInfo, new RecordItemIndex(0));
            repo.MDIPrincipal.BtI_nformacionAutorizaciones.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ModuloDeInformacion.Txt_Volante' at Center.", repo.ModuloDeInformacion.Txt_VolanteInfo, new RecordItemIndex(1));
            repo.ModuloDeInformacion.Txt_Volante.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Volante' with focus on 'ModuloDeInformacion.Txt_Volante'.", repo.ModuloDeInformacion.Txt_VolanteInfo, new RecordItemIndex(2));
            repo.ModuloDeInformacion.Txt_Volante.PressKeys(Volante);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ModuloDeInformacion.BtConsultar' at Center.", repo.ModuloDeInformacion.BtConsultarInfo, new RecordItemIndex(3));
            repo.ModuloDeInformacion.BtConsultar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ModuloDeInformacion.Cerrar' at Center.", repo.ModuloDeInformacion.CerrarInfo, new RecordItemIndex(4));
            repo.ModuloDeInformacion.Cerrar.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
