///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ProcesoAutorizaciones1 recording.
    /// </summary>
    [TestModule("7e8fc83c-9ea9-4946-bdd0-9c1f9a47600e", ModuleType.Recording, 1)]
    public partial class ProcesoAutorizaciones1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static ProcesoAutorizaciones1 instance = new ProcesoAutorizaciones1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ProcesoAutorizaciones1()
        {
            ModuloDestino = "Cuentas Médicas";
            Causal = "Solicitud de Gestión";
            Observacion = "Prueba Autorizaciones";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ProcesoAutorizaciones1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _ModuloDestino;

        /// <summary>
        /// Gets or sets the value of variable ModuloDestino.
        /// </summary>
        [TestVariable("4e4c8165-9d43-4ed6-a69c-13d1199c34f9")]
        public string ModuloDestino
        {
            get { return _ModuloDestino; }
            set { _ModuloDestino = value; }
        }

        string _Observacion;

        /// <summary>
        /// Gets or sets the value of variable Observacion.
        /// </summary>
        [TestVariable("8bd803d2-8e6e-4ba1-be74-91474c073122")]
        public string Observacion
        {
            get { return _Observacion; }
            set { _Observacion = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Causal.
        /// </summary>
        [TestVariable("9301c1a1-c31d-41ac-b839-dd98e8d714b5")]
        public string Causal
        {
            get { return repo.Causal; }
            set { repo.Causal = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormHash32770.Btn_AceptarVolanteAutor' at Center.", repo.FormHash32770.Btn_AceptarVolanteAutorInfo, new RecordItemIndex(0));
            repo.FormHash32770.Btn_AceptarVolanteAutor.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Causal' with focus on 'MDIPrincipal.Lbl_CausalAutorizaciones'.", repo.MDIPrincipal.Lbl_CausalAutorizacionesInfo, new RecordItemIndex(1));
            repo.MDIPrincipal.Lbl_CausalAutorizaciones.PressKeys(Causal);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ModuloDestino' with focus on 'MDIPrincipal.Lbl_ModuloDestinoAutorizaciones'.", repo.MDIPrincipal.Lbl_ModuloDestinoAutorizacionesInfo, new RecordItemIndex(2));
            repo.MDIPrincipal.Lbl_ModuloDestinoAutorizaciones.PressKeys(ModuloDestino);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Observacion' with focus on 'MDIPrincipal.Txt_ObservacionAutorizaciones'.", repo.MDIPrincipal.Txt_ObservacionAutorizacionesInfo, new RecordItemIndex(3));
            repo.MDIPrincipal.Txt_ObservacionAutorizaciones.PressKeys(Observacion);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Btn_AignarAutorizaciones' at Center.", repo.MDIPrincipal.Btn_AignarAutorizacionesInfo, new RecordItemIndex(4));
            repo.MDIPrincipal.Btn_AignarAutorizaciones.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormHash32770.Btn_AceptarVolanteAutor' at Center.", repo.FormHash32770.Btn_AceptarVolanteAutorInfo, new RecordItemIndex(5));
            repo.FormHash32770.Btn_AceptarVolanteAutor.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
