///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("6e8c6e24-d1c2-497a-9fea-5d0ea2d9ae5d", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable MenuItem.
        /// </summary>
        [TestVariable("aabc01ea-ec93-4de2-ab96-733731c89f7e")]
        public string MenuItem
        {
            get { return repo.MenuItem; }
            set { repo.MenuItem = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Archivo' at 17;10.", repo.MDIPrincipal.ArchivoInfo, new RecordItemIndex(0));
            repo.MDIPrincipal.Archivo.Click("17;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IQCuentasMedicas.CapturaAtencionesYServicios' at 78;79.", repo.IQCuentasMedicas.CapturaAtencionesYServiciosInfo, new RecordItemIndex(1));
            repo.IQCuentasMedicas.CapturaAtencionesYServicios.Click("78;79");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Panel2.Iniciar' at 42;14.", repo.MDIPrincipal.Panel2.IniciarInfo, new RecordItemIndex(2));
            repo.MDIPrincipal.Panel2.Iniciar.Click("42;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MDIPrincipal.Panel2.CodigoHomologoFila0' at 38;7.", repo.MDIPrincipal.Panel2.CodigoHomologoFila0Info, new RecordItemIndex(3));
            repo.MDIPrincipal.Panel2.CodigoHomologoFila0.DoubleClick("38;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmBusquedaServicio.Text' at 41;10.", repo.FrmBusquedaServicio.TextInfo, new RecordItemIndex(4));
            repo.FrmBusquedaServicio.Text.Click("41;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'L04AC073103' with focus on 'FrmBusquedaServicio.Text'.", repo.FrmBusquedaServicio.TextInfo, new RecordItemIndex(5));
            repo.FrmBusquedaServicio.Text.PressKeys("L04AC073103");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmBusquedaServicio.Buscar' at 55;11.", repo.FrmBusquedaServicio.BuscarInfo, new RecordItemIndex(6));
            repo.FrmBusquedaServicio.Buscar.Click("55;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmBusquedaServicio.Buscar' at -714;111.", repo.FrmBusquedaServicio.BuscarInfo, new RecordItemIndex(7));
            repo.FrmBusquedaServicio.Buscar.Click("-714;111");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Panel2.Salir' at 51;8.", repo.MDIPrincipal.Panel2.SalirInfo, new RecordItemIndex(8));
            repo.MDIPrincipal.Panel2.Salir.Click("51;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomologacionManual.ButtonSi' at 34;11.", repo.HomologacionManual.ButtonSiInfo, new RecordItemIndex(9));
            repo.HomologacionManual.ButtonSi.Click("34;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.MdiClient' at 1038;690.", repo.MDIPrincipal.MdiClientInfo, new RecordItemIndex(10));
            repo.MDIPrincipal.MdiClient.Click("1038;690");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.LineaArriba' at 43;-99.", repo.Explorer.LineaArribaInfo, new RecordItemIndex(11));
            repo.Explorer.LineaArriba.Click("43;-99");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
