///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AbrirVentanaAutorizaciones recording.
    /// </summary>
    [TestModule("942795be-9e67-455c-81e3-76bb83cac274", ModuleType.Recording, 1)]
    public partial class AbrirVentanaAutorizaciones : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static AbrirVentanaAutorizaciones instance = new AbrirVentanaAutorizaciones();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AbrirVentanaAutorizaciones()
        {
            FolderId = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AbrirVentanaAutorizaciones Instance
        {
            get { return instance; }
        }

#region Variables

        string _FolderId;

        /// <summary>
        /// Gets or sets the value of variable FolderId.
        /// </summary>
        [TestVariable("ec1211dd-791a-495f-8b30-b61451bf3a3d")]
        public string FolderId
        {
            get { return _FolderId; }
            set { _FolderId = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.BtnImagenes_Autor' at Center.", repo.MDIPrincipal.BtnImagenes_AutorInfo, new RecordItemIndex(0));
            repo.MDIPrincipal.BtnImagenes_Autor.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'VisorDeImagenesIQOutsourcing.SomeContainer' at 260;127.", repo.VisorDeImagenesIQOutsourcing.SomeContainerInfo, new RecordItemIndex(1));
            repo.VisorDeImagenesIQOutsourcing.SomeContainer.Click(System.Windows.Forms.MouseButtons.Right, "260;127");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IQCuentasMedicas.DatosImagen' at 50;8.", repo.IQCuentasMedicas.DatosImagenInfo, new RecordItemIndex(2));
            repo.IQCuentasMedicas.DatosImagen.Click("50;8");
            Delay.Milliseconds(0);
            
            ObtenerFolderID();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VisorDeImagenesIQOutsourcing.Cerrar' at Center.", repo.VisorDeImagenesIQOutsourcing.CerrarInfo, new RecordItemIndex(4));
            repo.VisorDeImagenesIQOutsourcing.Cerrar.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
