///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AbrirVentanaInfo recording.
    /// </summary>
    [TestModule("ed6634a9-ba06-46f4-a900-850ff6605bfc", ModuleType.Recording, 1)]
    public partial class AbrirVentanaInfo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static AbrirVentanaInfo instance = new AbrirVentanaInfo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AbrirVentanaInfo()
        {
            FolderId = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AbrirVentanaInfo Instance
        {
            get { return instance; }
        }

#region Variables

        string _FolderId;

        /// <summary>
        /// Gets or sets the value of variable FolderId.
        /// </summary>
        [TestVariable("d85d4af4-80cb-4fd6-84db-ea2dbd1e3b17")]
        public string FolderId
        {
            get { return _FolderId; }
            set { _FolderId = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'MDIPrincipal.Panel1.SomeElement' at 469;95.", repo.MDIPrincipal.Panel1.SomeElementInfo, new RecordItemIndex(0));
            repo.MDIPrincipal.Panel1.SomeElement.Click(System.Windows.Forms.MouseButtons.Right, "469;95");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IQCuentasMedicas.DatosImagen' at 50;12.", repo.IQCuentasMedicas.DatosImagenInfo, new RecordItemIndex(1));
            repo.IQCuentasMedicas.DatosImagen.Click("50;12");
            Delay.Milliseconds(0);
            
            ObtenerFolderID();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
