///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AutorizacionesVolante recording.
    /// </summary>
    [TestModule("de3cd8e8-6c5e-4001-853c-62e1d433d6b7", ModuleType.Recording, 1)]
    public partial class AutorizacionesVolante : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static AutorizacionesVolante instance = new AutorizacionesVolante();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AutorizacionesVolante()
        {
            Volante = "141031331";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AutorizacionesVolante Instance
        {
            get { return instance; }
        }

#region Variables

        string _Volante;

        /// <summary>
        /// Gets or sets the value of variable Volante.
        /// </summary>
        [TestVariable("d181bf50-083c-4247-a95f-f0ffe694faec")]
        public string Volante
        {
            get { return _Volante; }
            set { _Volante = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Nservicios.
        /// </summary>
        [TestVariable("b62ab2f8-0bec-4c1e-a453-20f1779c3aab")]
        public string Nservicios
        {
            get { return repo.Nservicios; }
            set { repo.Nservicios = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.FilaFila1' at Center.", repo.MDIPrincipal.FilaFila1Info, new RecordItemIndex(0));
            repo.MDIPrincipal.FilaFila1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Btn_Asociar1' at Center.", repo.MDIPrincipal.Btn_Asociar1Info, new RecordItemIndex(1));
            repo.MDIPrincipal.Btn_Asociar1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmAgregarVolantes.BtAdicionar' at Center.", repo.FrmAgregarVolantes.BtAdicionarInfo, new RecordItemIndex(2));
            repo.FrmAgregarVolantes.BtAdicionar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MensajeBloqueante.Aceptar' at Center.", repo.MensajeBloqueante.AceptarInfo, new RecordItemIndex(3));
            repo.MensajeBloqueante.Aceptar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmAgregarVolantes.Cerrar' at Center.", repo.FrmAgregarVolantes.CerrarInfo, new RecordItemIndex(4));
            repo.FrmAgregarVolantes.Cerrar.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
