///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CuentasMedicas_Sanitas
{
	public partial class CargaAtencionFolder
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void CargaDatos()
		{
			string folderid=ParFolderId;
			if (SolicitudID==folderid){
				
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.FechaIni' at Center.", repo.MDIPrincipal.Row1.FechaIniInfo, new RecordItemIndex(0));
            repo.MDIPrincipal.Row1.FechaIni.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.FechaIni' at Center.", repo.MDIPrincipal.Row1.FechaIniInfo, new RecordItemIndex(2));
            repo.MDIPrincipal.Row1.FechaIni.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FechaInicio' with focus on 'MDIPrincipal.Row1.FechaIni'.", repo.MDIPrincipal.Row1.FechaIniInfo, new RecordItemIndex(3));
            repo.MDIPrincipal.Row1.FechaIni.PressKeys(FechaInicio);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.FechaFin' at Center.", repo.MDIPrincipal.Row1.FechaFinInfo, new RecordItemIndex(4));
            repo.MDIPrincipal.Row1.FechaFin.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FechaFin' with focus on 'MDIPrincipal.Row1.FechaFin'.", repo.MDIPrincipal.Row1.FechaFinInfo, new RecordItemIndex(5));
            repo.MDIPrincipal.Row1.FechaFin.PressKeys(FechaFin);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.NumeroIdentificacion' at Center.", repo.MDIPrincipal.Row1.NumeroIdentificacionInfo, new RecordItemIndex(7));
            repo.MDIPrincipal.Row1.NumeroIdentificacion.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NroIdentificacion'.", new RecordItemIndex(8));
            Keyboard.Press(NroIdentificacion);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.TipoDeIdentificacionId' at Center.", repo.MDIPrincipal.Row1.TipoDeIdentificacionIdInfo, new RecordItemIndex(9));
            repo.MDIPrincipal.Row1.TipoDeIdentificacionId.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TipoIdentificacion'.", new RecordItemIndex(10));
            Keyboard.Press(TipoIdentificacion);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.PrimerApellido' at Center.", repo.MDIPrincipal.Row1.PrimerApellidoInfo, new RecordItemIndex(11));
            repo.MDIPrincipal.Row1.PrimerApellido.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(12));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'FFFF'.", new RecordItemIndex(13));
            Keyboard.Press("FFFF");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'MDIPrincipal.Row1.NombreContenido'", repo.MDIPrincipal.Row1.NombreContenidoInfo, new ActionTimeout(5000), new RecordItemIndex(14));
            repo.MDIPrincipal.Row1.NombreContenidoInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.ValorBruto' at Center.", repo.MDIPrincipal.Row1.ValorBrutoInfo, new RecordItemIndex(15));
            repo.MDIPrincipal.Row1.ValorBruto.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ValorBruto'.", new RecordItemIndex(16));
            Keyboard.Press(ValorBruto);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Row1.ValorNeto' at Center.", repo.MDIPrincipal.Row1.ValorNetoInfo, new RecordItemIndex(17));
            repo.MDIPrincipal.Row1.ValorNeto.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ValorBruto'.", new RecordItemIndex(18));
            Keyboard.Press(ValorBruto);
            Delay.Milliseconds(0);
				
			}
			
		}
		
	}

}

