///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CargaAtencionFolder recording.
    /// </summary>
    [TestModule("68f69d69-81e5-4aee-bf2c-ccb6070f8639", ModuleType.Recording, 1)]
    public partial class CargaAtencionFolder : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static CargaAtencionFolder instance = new CargaAtencionFolder();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CargaAtencionFolder()
        {
            SolicitudID = "";
            ParFolderId = "";
            FechaInicio = "";
            FechaFin = "";
            TipoIdentificacion = "";
            ValorBruto = "";
            NroIdentificacion = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CargaAtencionFolder Instance
        {
            get { return instance; }
        }

#region Variables

        string _SolicitudID;

        /// <summary>
        /// Gets or sets the value of variable SolicitudID.
        /// </summary>
        [TestVariable("c2569a24-2ce7-404c-be2d-8c80a0d561e8")]
        public string SolicitudID
        {
            get { return _SolicitudID; }
            set { _SolicitudID = value; }
        }

        string _ParFolderId;

        /// <summary>
        /// Gets or sets the value of variable ParFolderId.
        /// </summary>
        [TestVariable("d231342c-7bc1-4196-aee8-6e3dd20d0f23")]
        public string ParFolderId
        {
            get { return _ParFolderId; }
            set { _ParFolderId = value; }
        }

        string _FechaInicio;

        /// <summary>
        /// Gets or sets the value of variable FechaInicio.
        /// </summary>
        [TestVariable("4c4b942d-c041-4597-84cd-4eb77aa8384c")]
        public string FechaInicio
        {
            get { return _FechaInicio; }
            set { _FechaInicio = value; }
        }

        string _FechaFin;

        /// <summary>
        /// Gets or sets the value of variable FechaFin.
        /// </summary>
        [TestVariable("f074d2a9-440f-4023-afb8-421991b6e930")]
        public string FechaFin
        {
            get { return _FechaFin; }
            set { _FechaFin = value; }
        }

        string _TipoIdentificacion;

        /// <summary>
        /// Gets or sets the value of variable TipoIdentificacion.
        /// </summary>
        [TestVariable("1a4fadaf-15ac-4d1e-b92b-55b2aff6e4fc")]
        public string TipoIdentificacion
        {
            get { return _TipoIdentificacion; }
            set { _TipoIdentificacion = value; }
        }

        string _ValorBruto;

        /// <summary>
        /// Gets or sets the value of variable ValorBruto.
        /// </summary>
        [TestVariable("158902ad-3db5-4685-ac97-752e42da1337")]
        public string ValorBruto
        {
            get { return _ValorBruto; }
            set { _ValorBruto = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NroIdentificacion.
        /// </summary>
        [TestVariable("f9020e78-5832-4ba4-9d5a-447ad85c2812")]
        public string NroIdentificacion
        {
            get { return repo.NroIdentificacion; }
            set { repo.NroIdentificacion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            CargaDatos();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
