///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CargaServSinHomologar recording.
    /// </summary>
    [TestModule("7d933712-2ad4-486e-bc81-0592cd49986c", ModuleType.Recording, 1)]
    public partial class CargaServSinHomologar : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static CargaServSinHomologar instance = new CargaServSinHomologar();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CargaServSinHomologar()
        {
            VlrUnitario = "55590";
            DescripcionServ = "prueba";
            NroIdentificacionOriginal = "";
            NroIdentificacion = "";
            CodServicio = "12345";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CargaServSinHomologar Instance
        {
            get { return instance; }
        }

#region Variables

        string _VlrUnitario;

        /// <summary>
        /// Gets or sets the value of variable VlrUnitario.
        /// </summary>
        [TestVariable("5814c72e-2749-45f6-b0d8-3088360624b4")]
        public string VlrUnitario
        {
            get { return _VlrUnitario; }
            set { _VlrUnitario = value; }
        }

        string _DescripcionServ;

        /// <summary>
        /// Gets or sets the value of variable DescripcionServ.
        /// </summary>
        [TestVariable("7fc93e55-0a4b-4ca9-8069-ae5e335b649e")]
        public string DescripcionServ
        {
            get { return _DescripcionServ; }
            set { _DescripcionServ = value; }
        }

        string _NroIdentificacionOriginal;

        /// <summary>
        /// Gets or sets the value of variable NroIdentificacionOriginal.
        /// </summary>
        [TestVariable("5ffab27e-1cfa-4e51-9589-c6a7b1c06307")]
        public string NroIdentificacionOriginal
        {
            get { return _NroIdentificacionOriginal; }
            set { _NroIdentificacionOriginal = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable CodServicio.
        /// </summary>
        [TestVariable("1c08caca-7405-4485-a517-a7b7060789e7")]
        public string CodServicio
        {
            get { return repo.CodServicio; }
            set { repo.CodServicio = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NroIdentificacion.
        /// </summary>
        [TestVariable("83838b50-a51c-44ad-a023-ef2f7fcc8e8d")]
        public string NroIdentificacion
        {
            get { return repo.NroIdentificacion; }
            set { repo.NroIdentificacion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            CargaServicios();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
