///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ProcesoAutoFolder recording.
    /// </summary>
    [TestModule("19d09214-30a9-459a-a665-937ae8d7e095", ModuleType.Recording, 1)]
    public partial class ProcesoAutoFolder : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static ProcesoAutoFolder instance = new ProcesoAutoFolder();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ProcesoAutoFolder()
        {
            ParFolderId = "";
            SolicitudID = "";
            Causal = "";
            ModuloDestino = "";
            Observacion = "";
            IDAtencion = "";
            IDAtencionOriginal = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ProcesoAutoFolder Instance
        {
            get { return instance; }
        }

#region Variables

        string _ParFolderId;

        /// <summary>
        /// Gets or sets the value of variable ParFolderId.
        /// </summary>
        [TestVariable("936cf32c-d13c-497d-a0ec-7986c26493ae")]
        public string ParFolderId
        {
            get { return _ParFolderId; }
            set { _ParFolderId = value; }
        }

        string _SolicitudID;

        /// <summary>
        /// Gets or sets the value of variable SolicitudID.
        /// </summary>
        [TestVariable("35f31716-3dad-4a1b-8d12-954cd93c4b89")]
        public string SolicitudID
        {
            get { return _SolicitudID; }
            set { _SolicitudID = value; }
        }

        string _ModuloDestino;

        /// <summary>
        /// Gets or sets the value of variable ModuloDestino.
        /// </summary>
        [TestVariable("5668fe16-afd8-4cad-bcb4-62107c0154aa")]
        public string ModuloDestino
        {
            get { return _ModuloDestino; }
            set { _ModuloDestino = value; }
        }

        string _Observacion;

        /// <summary>
        /// Gets or sets the value of variable Observacion.
        /// </summary>
        [TestVariable("c36fd7f0-3e4e-46d5-a667-9cda5d14edb1")]
        public string Observacion
        {
            get { return _Observacion; }
            set { _Observacion = value; }
        }

        string _IDAtencion;

        /// <summary>
        /// Gets or sets the value of variable IDAtencion.
        /// </summary>
        [TestVariable("9d1f08a1-86f7-461b-afca-ed3a6043fd88")]
        public string IDAtencion
        {
            get { return _IDAtencion; }
            set { _IDAtencion = value; }
        }

        string _IDAtencionOriginal;

        /// <summary>
        /// Gets or sets the value of variable IDAtencionOriginal.
        /// </summary>
        [TestVariable("29cfc9fb-3b63-4986-9e49-80ce1205bedc")]
        public string IDAtencionOriginal
        {
            get { return _IDAtencionOriginal; }
            set { _IDAtencionOriginal = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Causal.
        /// </summary>
        [TestVariable("720b35f9-0ae2-41ca-8eae-6025b477902c")]
        public string Causal
        {
            get { return repo.Causal; }
            set { repo.Causal = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            CargaDatos();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
