///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CuentasMedicas_Sanitas
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RecorrerServicios recording.
    /// </summary>
    [TestModule("94aa3394-c8ee-47a0-8de4-3060e8ea2d0e", ModuleType.Recording, 1)]
    public partial class RecorrerServicios : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CuentasMedicas_SanitasRepository repository.
        /// </summary>
        public static CuentasMedicas_SanitasRepository repo = CuentasMedicas_SanitasRepository.Instance;

        static RecorrerServicios instance = new RecorrerServicios();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RecorrerServicios()
        {
            CodServicioHomologo = "L04AC073103";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RecorrerServicios Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable CodServicio.
        /// </summary>
        [TestVariable("1c08caca-7405-4485-a517-a7b7060789e7")]
        public string CodServicio
        {
            get { return repo.CodServicio; }
            set { repo.CodServicio = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable CodServicioHomologo.
        /// </summary>
        [TestVariable("57f30d41-9b16-4eea-b49c-24fceb16ed3a")]
        public string CodServicioHomologo
        {
            get { return repo.CodServicioHomologo; }
            set { repo.CodServicioHomologo = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MDIPrincipal.Panel2.CodigoHomologoFila' at 38;7.", repo.MDIPrincipal.Panel2.CodigoHomologoFilaInfo, new RecordItemIndex(0));
            repo.MDIPrincipal.Panel2.CodigoHomologoFila.DoubleClick("38;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmBusquedaServicio.Text' at 41;10.", repo.FrmBusquedaServicio.TextInfo, new RecordItemIndex(1));
            repo.FrmBusquedaServicio.Text.Click("41;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CodServicioHomologo' with focus on 'FrmBusquedaServicio.Text'.", repo.FrmBusquedaServicio.TextInfo, new RecordItemIndex(2));
            repo.FrmBusquedaServicio.Text.PressKeys(CodServicioHomologo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmBusquedaServicio.Buscar' at 55;11.", repo.FrmBusquedaServicio.BuscarInfo, new RecordItemIndex(3));
            repo.FrmBusquedaServicio.Buscar.Click("55;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmBusquedaServicio.Buscar' at -714;111.", repo.FrmBusquedaServicio.BuscarInfo, new RecordItemIndex(4));
            repo.FrmBusquedaServicio.Buscar.Click("-714;111");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Panel2.Guardar' at Center.", repo.MDIPrincipal.Panel2.GuardarInfo, new RecordItemIndex(5));
            //repo.MDIPrincipal.Panel2.Guardar.Click();
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
